# Generated by Django 5.0.14 on 2026-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_joined_school_user_full_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='skills',
            field=models.TextField(blank=True, help_text="List the teacher's skills and acquired competencies (comma-separated)."),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profession_details',
            field=models.TextField(blank=True, help_text="Describe the teacher's professional background and qualifications."),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select subjects taught.', to='core.subject'),
        ),
    ]
